server:
  port: 8080
spring:
  application:
    name: java-project-template
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java_project_template?serverTimezone=Asia/Shanghai
  profiles:
    include:
      - knife4j
      - mybatis
logging:
  config: classpath:logback-spring.xml